function cellInfo = helperCreateLaneBoundariesLC(varargin) 
% Part of set up script for the Lane Change Example
%
% it returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 
%
%   This is a helper for example purposes and may be removed or
%   modified in the future.

%   Copyright 2019 The MathWorks, Inc.

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'BusLaneBoundaries1', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'NumLaneBoundaries', [1 1], 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Time', [1 1], 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'LaneBoundaries', [5 1], 'Bus: BusLaneBoundaries1LaneBoundaries', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'BusLaneBoundaries1LaneBoundaries', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'Coordinates', [121 3], 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Curvature', [121 1], 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'CurvatureDerivative', [121 1], 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'HeadingAngle', [1 1], 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'LateralOffset', [1 1], 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BoundaryType', [1 1], 'uint8', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Strength', [1 1], 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Width', [1 1], 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Length', [1 1], 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Space', [1 1], 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
