function [scenario, egoVehicle] = ACC_02_ISO_AutoRetargetTest()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.9 (R2020b) and Automated Driving Toolbox 3.2 (R2020b).
% Generated on: 30-Nov-2020 12:51:26

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [0 0 0;
    300 0 0];
laneSpecification = lanespec(2);
road(scenario, roadCenters, 'Lanes', laneSpecification);

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [0 1.8 0], ...
    'FrontOverhang', 0.9, ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'egoCar');
waypoints = [0 1.8 0;
    300 1.8 0];
speed = 15;
trajectory(egoVehicle, waypoints, speed);

% Add the non-ego actors
leadCar = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [43 1.8 0], ...
    'FrontOverhang', 0.9, ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'leadCar');
waypoints = [43 1.8 0;
    126.4 1.8 0;
    127.4 1.8 0;
    151 -1.8 0;
    152 -1.8 0;
    293 -1.8 0];
speed = 13.9;
trajectory(leadCar, waypoints, speed);

thirdCar = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [155.5 1.8 0], ...
    'FrontOverhang', 0.9, ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'thirdCar');
waypoints = [155.5 1.8 0;
    168.1 1.8 0;
    193.3 1.8 0];
speed = 2.1;
trajectory(thirdCar, waypoints, speed);

