%%% Create new ensemble datastore from subset of existing ensemble datastore

%% Extract Specific Member from Ensemble Datastore
% Extract the ensemble member that you identify from an ensemble datastore and use a single read command to obtain the contents.
% For this example, use the following code to create a simulationEnsembleDatastore object using data previously generated by running a Simulink® model at a various fault values (see generateSimulationEnsemble). 
% The ensemble includes simulation data for five different values of a model parameter, ToothFaultGain. 
% Because of the volume of data, the unzip operation takes a few minutes.
unzip simEnsData.zip
ens = simulationEnsembleDatastore(pwd,'logsout')

ems_nm = ens.NumMembers

% The ensemble contains five files.
% Extract the fourth ensemble member into a new, single-member ensemble sens.
idx = 4;
sens = subset(ens,idx);
sens_nm = sens.NumMembers

% sens contains one member. View the file name to confirm the member index.
sens.Files

% Reset sens to the first member and read the contents.
reset(sens)
m4 = read(sens)

% m4 contains the data for the extracted member.

%% Create Subset of Ensemble Datastore
% Create a simulation ensemble datastore from a subset of an existing simulation ensemble datastore.
% Create a simulationEnsembleDatastore object using data previously generated by running a Simulink® model at various fault values.
unzip simEnsData.zip
ens = simulationEnsembleDatastore(pwd,'logsout');
ens_nm = ens.NumMembers

% The ensemble contains five files. View the file names.
ens.Files

% Extract the first, third, and fifth files into a new ensemble.
idx = [1 3 5];
sens = subset(ens,idx);
sens_nm = sens.NumMembers

% The new ensemble contains three members. View the file names.
sens.Files

% The new ensemble contains the three files that you indexed.
